name: aisound-env
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - pip
  - pip:
      - fastapi
      - "uvicorn[standard]"
      - python-dotenv
      - pillow
      - python-multipart
      - pydantic
      - numpy
      - typing_extensions
      - tensorflow
